modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "projectrpg"
version = "${version}"
displayName = "Project RPG"
authors = "Wagon, BoonelDanForever, Vik, AnonMine"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "modlogo.png"

[[dependencies.projectrpg]]
modId = "forge"
mandatory = false
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projectrpg]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projectrpg]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"