modLoader="javafml"
loaderVersion="[43,)" 
license="All rights reserved"
[[mods]]
    modId="projectdnd"
    version="${file.jarVersion}"
    displayName="Project D&D"
    logoFile="modlogo.png"
    credits="N/A"
    authors="Wagon, BoonelDanForever, Vik, AnonMine"
    description='''
Descriptor

'''

[[dependencies.projectdnd]]
    modId="forge"
    mandatory=false
    versionRange="[43,)"
    ordering="BEFORE"
    side="BOTH"
