modLoader="javafml"
loaderVersion="[41,)" 
license="All rights reserved"
[[mods]]
    modId="projectdnd"
    version="${file.jarVersion}"
    displayName="Project D&D"
    logoFile="modlogo.png"
    credits="N/A"
    authors="Wagon, BoonelDanForever, Vik, AnonMine"
    description='''
Descriptor

'''

[[dependencies.projectdnd]]
    modId=""
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"